# Generated by Django 4.2.5 on 2023-09-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_post_description_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='static/images/products/defPostImg.png', null=True, upload_to='static/images/products', verbose_name='Изображение'),
        ),
    ]
